---
title: "powerPlots"
author: "Sarah Deschamps"
date: "2025-07-03"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(bdots)
library(eyetrackSim)
library(xtable)
library(data.table)
library(ggplot2)
library(tidyr)
```

```{r make plots}
ff <- list.files("~/Desktop/2025-map/map2025/new_scripts/new_power/rds/", full.names = TRUE, pattern = "rds")

rlist <- lapply(ff, readRDS)
rr <- readRDS(ff[[1]])

extractSigTimes <- function(rr) {
  sm <- lapply(rr, `[[`, 1)
  mm <- lapply(rr, `[[`, 2)
  pm <- lapply(rr, `[[`, 3)
  #smtimes <- lapply(sm, `[[`, "sigTime")
  #mmtimes <- lapply(mm, `[[`, "sigTime")
  #pmtimes <- lapply(pm, `[[`, "sigTime")
  smtime <- lapply(sm, `[[`, 1)
  mmtime <- lapply(mm, `[[`, 1)
  pmtime <- lapply(pm, `[[`, 1)

  smdf <- as.data.frame(unlist(smtime))
  mmdf <- as.data.frame(unlist(mmtime))
  pmdf <- as.data.frame(unlist(pmtime))

  df <- data.frame(smdf, mmdf, pmdf)
  df_long <- pivot_longer(df,
                        cols = c(singlemeans,manymeans,permutation),
                        names_to = "mean_type",
                        values_to = "min_sig_time")
  return(df_long)
}

times <- lapply(rlist, extractSigTimes)


#ggplot(data = df_long, aes(x = min_sig_time, color = mean_type)) + geom_density()

ggplot(data = df_long, aes(x = min_sig_time, color = mean_type)) + stat_ecdf() + scale_color_manual(values = c("#0FA3B1", "#E07A5F", "#0A014F")) + xlim(min = -1.0, max = 1.0)
```

```{r calculate power}
slope <- attributes(rr)$simsettings$slope

powerdetector <- function(mm) {
  # type 2 error if no difference detected
  if (is.null(mm)) return(-200)
    
  # type 1 error if difference detected before true difference
  if (min(mm) < 0) {
    return(-100)
  }
    
  # if no error occurred, return the first difference detected
  return(min(mm))
}

smt <- vapply(sm, powerdetector, numeric(1))
mmt <- vapply(mm, powerdetector, numeric(1))
pmt <- vapply(pm, powerdetector, numeric(1))


makeSummary <- function(vv) {
  tie <- mean(vv == -100)
  t2e <- mean(vv == -200) 
  pwr <- 1 - mean(vv %in% c(-100, -200))
  ssm <- summary(vv[!(vv %in% c(-100, -200))])[c(1:3, 5:6)]
  ssm <- c(tie, t2e, pwr, ssm)
  names(ssm)[1:3] <- c("Type I Error", "Type II Error", "Power")
  ssm
}

list(
  sm = makeSummary(smt),
  mm = makeSummary(mmt),
  pm = makeSummary(pmt)
)
```

